language: go
sudo: false

go:
  - 1.11.x
  - 1.12.x
  - master

services:
  - redis
  - memcached
  - mongodb

before_install:
  - go get github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)
