language: go
sudo: false

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

services:
  - redis
  - memcached
  - mongodb

matrix:
  fast_finish: true
  include:
  - go: 1.12.x

before_install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/campoy/embedmd

install:
  - go get -t -v .

script:
  - dep ensure
  - embedmd -d *.md
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)
