[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/gomemcache"

[[constraint]]
  branch = "master"
  name = "github.com/bradleypeabody/gorilla-sessions-memcache"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/kidstuff/mongostore"

[[constraint]]
  name = "github.com/memcachier/mc"
  version = "2.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/quasoft/memstore"

[[constraint]]
  name = "github.com/skamenetskiy/redistore"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
